### ISSUE TITLE
Enable `no-constant-binary-expression`

### ISSUE THREAD

**Issue by codybrouwers** [vercel/style-guide#23]
When we upgrade ESLint to 8.14.0 we should enable this rule:
https://eslint.org/docs/rules/no-constant-binary-expression

I tried enabling it and found two instances of easy to fix bugs.

Saw this recommended in [this](https://twitter.com/captbaritone/status/1535695102667915264?s=21&t=rgNlla27rv1fbSdiZ1NByw) tweet

**Comment by kyh** [comment]
I saw the same tweet and came here to post it ahah
