### ISSUE TITLE
Enable `comments/require-description` rule

### ISSUE THREAD

**Issue by junyper** [vercel/style-guide#26]
We might want to consider setting the [require-description](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html) rule to encourage adding a description to explain why an eslint rule has been disabled. That might be best set as a warning vs an error since we will probably have a lot of failures to address.

**Comment by mrmckeb** [comment]
Thanks for this @junyper!

We already use the plugin itself here:
https://github.com/vercel/style-guide/blob/canary/eslint/_base.js#L13

I love the idea of adding this rule, but we'll need to get more feedback before progressing.

**Comment by junyper** [comment]
Ok. I edited this to reflect adding just that one rule.

**Comment by mrmckeb** [comment]
We still plan to do this, but want to add a codemod for this first.
