### ISSUE TITLE
Enable `singleAttributePerLine`

### ISSUE THREAD

**Issue by mrmckeb** [vercel/style-guide#3]
Added in 2.6, this rule spreads attributes over multiple lines for any HTML/JSX tag with more than one attribute.

This is likely to be controversial, but very interested to hear feedback on this.

Example:
```html
<!-- Prettier 2.6, with `{"singleAttributePerLine": false}` -->
<div data-a="1">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</div>
<div data-a="1" data-b="2" data-c="3">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</div>

<!-- Prettier 2.6, with `{"singleAttributePerLine": true}` -->
<div data-a="1">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</div>
<div
  data-a="1"
  data-b="2"
  data-c="3"
>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</div>
```

https://prettier.io/docs/en/options.html#single-attribute-per-line

**Comment by dglsparsons** [comment]
I was pretty surprised to see this as it seems to _somewhat_ go against their [option philosophy](https://prettier.io/docs/en/option-philosophy.html). 

Reading [the discussion](https://github.com/prettier/prettier/issues/5501) though, it seems like support for it is overwhelmingly positive. 

I wouldn't be surprised to see this become the default in the future.

**Comment by LaurentMag** [comment]
i'am confused about how do you enable that option ? i would also prefer to force 1 jsx attribute per line, but i see this option nowhere

Anyone can explain ? 

thanks !

**Comment by mrmckeb** [comment]
Hi @LaurentMag! It's from here:
https://prettier.io/docs/en/options.html#single-attribute-per-line

**Comment by mrmckeb** [comment]
We're closing this off after an internal conversation, as most people felt that this would not offer a huge advantage.
