### ISSUE TITLE
Configure `fixStyle` in `consistent-type-imports` 

### ISSUE THREAD

**Issue by mrmckeb** [vercel/style-guide#38]
This will allow us to default on the cleaner inline type imports, removing duplicate imports.

**Comment by mrmckeb** [comment]
This hasn't been released yet.

**Comment by mrmckeb** [comment]
it looks like this has actually landed here:
- https://github.com/typescript-eslint/typescript-eslint/pull/5050
- https://typescript-eslint.io/rules/consistent-type-imports#fixstyle

**Comment by snewcomer** [comment]
🥳

And likely you will want these two rules + configs to complete a migration on a codebase!  Still waiting for # 2475 but very close!

https://github.com/import-js/eslint-plugin-import/pull/2475
https://github.com/import-js/eslint-plugin-import/pull/2473

**Comment by mrmckeb** [comment]
Can't wait, thanks @snewcomer! Less lines of imports is a win.

**Comment by mrmckeb** [comment]
We'll close this off in favour of codemods (coming in future).
