### ISSUE TITLE
Adding a new preset for Testing Library

### ISSUE THREAD

**Issue by Belco90** [vercel/style-guide#53]
Hi there 👋. I'd like to propose a new preset for Testing Library: `@vercel/style-guide/eslint/testing-library`

This preset would enable the following plugins:
- [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library) with:
  - recommended rules for React
  - [no-global-regexp-flag-in-query](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-global-regexp-flag-in-query.md)
  - [no-manual-cleanup](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-manual-cleanup.md)
  - [prefer-explicit-assert](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-explicit-assert.md)
  - [prefer-user-event](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-user-event.md)
- [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom) with recommended rules

These plugins would be enabled only on testing files:
`['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[jt]s?(x)'],`

Thoughts? I'd be happy to create a PR to add this new preset.

**Comment by mrmckeb** [comment]
Hi @Belco90, we already have some of this enabled as a part of our Jest preset here:
https://github.com/vercel/style-guide/blob/canary/eslint/jest.js#L3-L23

As we use a mixture of Jest and Vitest internally, it may make sense to separate that out though.

**Comment by Belco90** [comment]
Oh, I didn't realize it was already part of the Jest preset!

I agree that it makes sense to separate them, so I'll create a small PR to do so and get some feedback. Thanks!
