### ISSUE TITLE
Consider adding rule to disallow configuration comments

### ISSUE THREAD

**Issue by mrmckeb** [vercel/style-guide#58]
This is currently an escape hatch, but could also be misused.

One option is `no-use` with an allow-list, but that plugin isn't well supported and some users report that the rule is currently broken.
https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/no-use.html

**Comment by EndangeredMassa** [comment]
These can be abused, but sometimes I do actually know better than the linter. I think this would get in the way more often than it would keep someone on the right path.

**Comment by mrmckeb** [comment]
We certainly couldn't roll `comments/no-use` out without allowing some/most of the comments that it disallows by default - the intention isn't to disallow `eslint-disable[-*]` comments.

I've updated the description to be clearer around what we are considering. We may need a custom rule for this.

**Comment by mrmckeb** [comment]
If we move forward with this, we'll only disallow:
- "eslint-disable"
- "eslint-disable-line"
- "eslint-disable-next-line"
