### ISSUE TITLE
Can we get a node.js specific typescript config? 

### ISSUE THREAD

**Issue by Ethan-Arrowood** [vercel/style-guide#59]
Would love a node.js specific typescript config that sets things like `moduleResolution: node`, and removes lib types like `DOM`. 

Maybe have one for cjs and another for esm too?

**Comment by Ethan-Arrowood** [comment]
Created one as an internal package in `vercel/vercel`: https://github.com/vercel/vercel/pull/9618/files#diff-85040292c249becb12e089a99413a0ef5ef344da8310ec211ed1a06afc2dc53c

let me know if y'all want me to contribute it here too. We should consider basing it off of the official tsconfig bases too

**Comment by mrmckeb** [comment]
I think that's a great idea, thanks @Ethan-Arrowood - it's something we had talked about too, but never got around to doing. We did the same inside of some of our internal repos.

We could make this TS5.x only, as it now supports multiple extends?
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#supporting-multiple-configuration-files-in-extends

(Sorry I missed this earlier)

**Comment by Ethan-Arrowood** [comment]
Sweet, I'll send a PR today 😄
