### ISSUE TITLE
Update typescript and typescript-eslint related dependencies

### ISSUE THREAD

**Issue by joulev** [vercel/style-guide#66]
TypeScript 5.1 has been out for a while now but `@vercel/style-guide` is still at peer dependency `typescript@^4.8.0`, causing warnings during installation:

```
 WARN  Issues with peer dependencies found
.
└─┬ @vercel/style-guide 4.0.2
  └── ✕ unmet peer typescript@^4.8.0: found 5.1.6
```

The `@typescript-eslint/typescript-estree` version used with `@vercel/style-guide` also doesn't support TypeScript 5.1

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.0.0

YOUR TYPESCRIPT VERSION: 5.1.6

Please only submit bug reports when using the officially supported version.

=============
```

I think it's time to release a new version with updated dependency and peer-dependency versions.

**Comment by matt-pawley** [comment]
👍 `prettier` version 3 is also now available and suffers the same problem.
