### ISSUE TITLE
Upgrade babel deps to fix security vuln in babel traverse

### ISSUE THREAD

**Issue by imoby** [vercel/style-guide#80]
Can we update the deps for babel to > 7.23.2 to fix the babel traverse vuln: https://github.com/advisories/GHSA-67hx-6x53-jw92

**Comment by movoid12** [comment]
Good point. I did that already for a project by running:

`pnpm audit fix` 

And i was able to update that and override and fix babel traverse vuln

**Comment by mrmckeb** [comment]
Thanks @movoid12, yes we left peers unpinned to enable people to upgrade.

I'll make this change soon in the package - thanks again!

**Comment by mrmckeb** [comment]
I forgot to link this, but it should have been solved by this merge, and will be in v6.0.
https://github.com/vercel/style-guide/pull/97
