### ISSUE TITLE
Proposal for removing deprecated `no-return-await` rule

### ISSUE THREAD

**Issue by AhmedBaset** [vercel/style-guide#88]
`no-return-await` [has been deprecated](https://eslint.org/docs/latest/rules/no-return-await) from eslint.

> This rule was deprecated in ESLint v8.46.0 with no replacement. The original intent of this rule no longer applies due to the fact JavaScript now handles native Promises differently. It can now be slower to remove await rather than keeping it. More technical information can be found in [this V8 blog entry](https://v8.dev/blog/fast-async).
> 
> Using return await inside an async function keeps the current function in the call stack until the Promise that is being awaited has resolved, at the cost of an extra microtask before resolving the outer Promise. return await can also be used in a try/catch statement to catch errors from another function that returns a Promise.
> 
> You can avoid the extra microtask by not awaiting the return value, with the trade off of the function no longer being a part of the stack trace if an error is thrown asynchronously from the Promise being returned. This can make debugging more difficult.

**Comment by mrmckeb** [comment]
Interesting, will create a PR now - thanks!
