### ISSUE TITLE
`it.only()` or `describe.only()` should fail lint

### ISSUE THREAD

**Issue by styfle** [vercel/style-guide#9]
Sometimes developers will use `it.only()` or `describe.only()` to run a single jest test locally but accidentally commit it to a PR and thus skip all tests except the one they're working on.

We should probably disable `it.skip()` as well for the same reason.

**Comment by styfle** [comment]
Here's an example of how to achieve this https://github.com/vercel/vercel/pull/4229

**Comment by adrianbw** [comment]
Yes, 100%.

**Comment by codybrouwers** [comment]
Good idea!

**Comment by ernestd** [comment]
+1 for `.skip` too

**Comment by mrmckeb** [comment]
Thanks for raising this @styfle! Can I confirm that this doesn't work with this style guide today?

We extend `plugin:jest/recommended`, which enables:
https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-disabled-tests.md

There's an example showing how to set up the `jest` config here:
https://github.com/vercel/style-guide#scoped-configuration-with-overrides

**Comment by styfle** [comment]
@mrmckeb I created this issue because I was reviewing a PR and it used `describe.only()` yet CI was passing.

**Comment by mrmckeb** [comment]
Ah, that repo didn't have the `jest` config. I've now added it.

CC @dglsparsons who was leading the charge on that part of our internal rollout.
